name: Test Parcel
on: 
  workflow_dispatch:
jobs:
  test-parcel:
    runs-on: ubuntu-18.04
    container: node:14-stretch
    steps:
      - uses: actions/checkout@v2.1.0
      - run: git clone https://github.com/kriszyp/parcel-segfault-repro.git
      - run: npm install
      - run: npm run build-js
      - run: npm link
      - run: cd parcel-segfault-repro && npm install && npm link lmdb && chmod 777 multiple.sh && ./multiple.sh
